Wired.Razor.MvcSample/Models/DemonstrationModel.cs
using System.Collections.Generic;

namespace Wired.Razor.MvcSample.Models
{
    public class DemonstrationModel
    {
        public IEnumerable<string> People { get; set; }
    }
}

Wired.Razor.MvcSample/Models/FooterModel.cs
using Wired.RazorPdf.Models;

namespace Wired.Razor.MvcSample.Models
{
    public class FooterModel : BaseModel
    {
        public string Name { get; set; }
    }
}

Wired.Razor.MvcSample/Models/HeaderModel.cs
using Wired.RazorPdf.Models;

namespace Wired.Razor.MvcSample.Models
{
    public class HeaderModel : BaseModel
    {
        public string Name { get; set; }
    }
}

Wired.Razor.MvcSample/Controllers/HomeController.cs
using System.Web.Mvc;

namespace Wired.Razor.MvcSample.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

Wired.Razor.MvcSample/Controllers/PdfController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using iTextSharp.text;
using Wired.Razor.MvcSample.Models;
using Wired.RazorPdf;
using Wired.RazorPdf.Snippets;
using Header = Wired.RazorPdf.Snippets.Header;

namespace Wired.Razor.MvcSample.Controllers
{
    public class PdfController : Controller
    {
        public ActionResult PdfWithoutLayout()
        {
            var generator = new MvcGenerator(ControllerContext, Server.MapPath("~"));

            var model = new FooterModel
            {
                Name = "Unicorns Rule"
            };

            var snippet = new Footer(model, "~/Views/Pdf/_Footer.cshtml", 50, 5, 5, 10);
            generator.AddPageSnippet(snippet);

            var pdf = generator.GeneratePdf(GetModel(), "PdfWithoutLayout");

            return new FileContentResult(pdf, "application/pdf");
        }

        public ActionResult PdfWithLayout()
        {
            var generator = new MvcGenerator(ControllerContext, Server.MapPath("~"));

            var model = new FooterModel
            {
                Name = "Unicorns Rule"
            };

            var snippet = new Footer(model, "~/Views/Pdf/_Footer.cshtml", 50, 5, 5, 10);
            generator.AddPageSnippet(snippet);

            var pdf = generator.GeneratePdf(GetModel(), "PdfWithLayout");

            return new FileContentResult(pdf, "application/pdf");
        }

        public ActionResult ControllerlessPdfWithoutLayout()
        {
            var generator = new StandaloneGenerator(new Parser(), Server.MapPath("~"));

            var model = new FooterModel
            {
                Name = "Unicorns Rule"
            };

            var snippet = new Footer(model, Server.MapPath("~/Views/Pdf/_Footer.cshtml"), 50, 5, 5, 10);
            generator.AddPageSnippet(snippet);

            var pdf = generator.GeneratePdf(GetModel(), Server.MapPath("~/Views/Pdf/ControllerlessPdfWithoutLayout.cshtml"));
            
            return new FileContentResult(pdf, "application/pdf");
        }

        public ActionResult LandscapeControllerlessPdfWithoutLayout()
        {
            var generator = new StandaloneGenerator(new Parser(), Server.MapPath("~"));

            var footerModel = new FooterModel
            {
                Name = "Unicorns Rule"
            };

            var headerModel = new HeaderModel
            {
                Name = "Unicorns Rule"
            };

            var footerSnippet = new Footer(footerModel, Server.MapPath("~/Views/Pdf/_Footer.cshtml"), 50, 5, 5, 10);
            var headerSnippet = new Header(headerModel, Server.MapPath("~/Views/Pdf/_Header.cshtml"), 50, 5, 5, 10);
            generator.AddPageSnippet(footerSnippet);
            generator.AddPageSnippet(headerSnippet);

            var pdf = generator.GeneratePdf(
                (writer, document) =>
                {
                    document.SetPageSize(PageSize.A4.Rotate());
                }, 
                GetModel(), 
                Server.MapPath("~/Views/Pdf/ControllerlessPdfWithoutLayout.cshtml"));

            return new FileContentResult(pdf, "application/pdf");
        }

        public ActionResult ControllerlessPdfWithLayout()
        {
            var generator = new StandaloneGenerator(new Parser(), Server.MapPath("~"))
            {
                Templates = new List<Template>
                {
                    new Template
                    {
                        Name = "~/Views/Shared/_PdfLayout.cshtml",
                        Source = System.IO.File.ReadAllText(Server.MapPath("~/Views/Shared/_PdfLayout.cshtml"))
                    }
                },
                Margins = new Margins(10, 10, 100, 10)
            };

            var footerModel = new FooterModel
            {
                Name = "Unicorns Rule"
            };

            var headerModel = new HeaderModel
            {
                Name = "Unicorns Rule"
            };

            var footerSnippet = new Footer(footerModel, Server.MapPath("~/Views/Pdf/_Footer.cshtml"), 80, 0, 0, 0);
            var headerSnippet = new Header(headerModel, Server.MapPath("~/Views/Pdf/_Header.cshtml"), 80, 0, 0, 0);
            generator.AddPageSnippet(footerSnippet);
            generator.AddPageSnippet(headerSnippet);

            var pdf = generator.GeneratePdf(GetModel(), Server.MapPath("~/Views/Pdf/ControllerlessPdfWithLayout.cshtml"));
            return new FileContentResult(pdf, "application/pdf");
        }

        private DemonstrationModel GetModel()
        {
            return new DemonstrationModel
            {
                People = new List<string> { "Alice", "Bob", "Charlie" }
            };
        }
    }
}

Wired.Razor.MvcSample/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>PDF Generator Demo</h1>
    <p class="lead">Let's make some PDFs!</p>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>PDF Without Layout</h2>
        @Html.ActionLink("Generate", "PdfWithoutLayout", "Pdf")
    </div>
    <div class="col-md-3">
        <h2>PDF With Layout</h2>
        @Html.ActionLink("Generate", "PdfWithLayout", "Pdf")
    </div>
    <div class="col-md-3">
        <h2>Controllerless PDF Without Layout</h2>
        @Html.ActionLink("Generate", "ControllerlessPdfWithoutLayout", "Pdf")
    </div>
    <div class="col-md-3">
        <h2>Controllerless PDF With Layout</h2>
        @Html.ActionLink("Generate", "ControllerlessPdfWithLayout", "Pdf")
    </div>
</div>

Wired.Razor.MvcSample/Views/Pdf/ControllerlessPdfWithLayout.cshtml
@model Wired.Razor.MvcSample.Models.DemonstrationModel

@{
    Layout = "~/Views/Shared/_PdfLayout.cshtml";
}

<h1>PDF With Layout</h1>

@foreach (var person in Model.People)
{
    <div>
        Person: @person
    </div>
}

<img src="~/Images/awesome.jpg" style="width: 680px; height: 383px;" alt="The most awesomest image ever" />

Wired.Razor.MvcSample/Views/Pdf/ControllerlessPdfWithoutLayout.cshtml
@model Wired.Razor.MvcSample.Models.DemonstrationModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PDF Without Layout</title>
</head>
<body>
    <h1>PDF Without Layout</h1>

    @foreach (var person in Model.People)
    {
        <div>
            Person: @person
        </div>
    }

    <img src="~/Images/awesome.jpg" style="width: 680px; height: 383px;" alt="The most awesomest image ever" />
</body>
</html>

Wired.Razor.MvcSample/Views/Pdf/PdfWithLayout.cshtml
@model Wired.Razor.MvcSample.Models.DemonstrationModel

@{
    Layout = "~/Views/Shared/_PdfLayout.cshtml";
}

<h1>PDF With Layout</h1>

@foreach (var person in Model.People)
{
    <div>
        Person: @person
    </div>
}

<img src="~/Images/awesome.jpg" style="width: 680px; height: 383px;" alt="The most awesomest image ever" />

Wired.Razor.MvcSample/Views/Pdf/PdfWithoutLayout.cshtml
@model Wired.Razor.MvcSample.Models.DemonstrationModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PDF Without Layout</title>
</head>
<body>
    <h1>PDF Without Layout</h1>

    @foreach (var person in Model.People)
    {
        <div>
            Person: @person
        </div>
    }

    <img src="~/Images/awesome.jpg" style="width: 680px; height: 383px;" alt="The most awesomest image ever" />
</body>
</html>

Wired.Razor.MvcSample/Views/Pdf/_Footer.cshtml
@model Wired.Razor.MvcSample.Models.FooterModel

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body>
    <div style="float: left;">
        <h2>@Model.Name</h2>
    </div>
    <div style="float: right">
        Footer - Page @Model.PageNumber
    </div>
</body>
</html>

Wired.Razor.MvcSample/Views/Pdf/_Header.cshtml
@model Wired.Razor.MvcSample.Models.HeaderModel
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
</head>
<body style="background-color: black; color: white;">
    <div style="float: left;">
        <h2>@Model.Name</h2>
        <div>(in the header!)</div>
    </div>
    <div style="float: right">
        Header - Page @Model.PageNumber
    </div>
</body>
</html>

Wired.Razor.MvcSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <meta name="description" content="Demo App" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Wired.Razor.MvcSample/Views/Shared/_PdfLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PDF Without Layout</title>
</head>
<body>
    @RenderBody()
</body>
</html>